Repository TeamBLife/B-Life, pull requests merged in 2024-03, with the labels that each got.

#8 Refac: ERD 구조 수정
  src/main/kotlin/com/blife/blife/domain/book/model/Book.kt
  src/main/kotlin/com/blife/blife/domain/book/model/LibBook.kt
  src/main/kotlin/com/blife/blife/domain/library/enums/REGION.kt
  src/main/kotlin/com/blife/blife/domain/library/model/Library.kt
Labels: Refactor

#10 Feat/#9
  build.gradle.kts
  src/main/kotlin/com/blife/blife/domain/member/controller/MemberController.kt
  src/main/kotlin/com/blife/blife/domain/member/dto/LoginResponse.kt
  src/main/kotlin/com/blife/blife/domain/member/dto/MemberLoginRequest.kt
  src/main/kotlin/com/blife/blife/domain/member/dto/MemberRespose.kt
  src/main/kotlin/com/blife/blife/domain/member/dto/MemberSignupRequest.kt
  src/main/kotlin/com/blife/blife/domain/member/enums/MemberRole.kt
  src/main/kotlin/com/blife/blife/domain/member/model/Member.kt
  src/main/kotlin/com/blife/blife/domain/member/repository/MemberRepository.kt
  src/main/kotlin/com/blife/blife/domain/member/service/MemberService.kt
  src/main/kotlin/com/blife/blife/global/config/PasswordEncoderConfig.kt
  src/main/kotlin/com/blife/blife/global/config/SecurityConfig.kt
  src/main/kotlin/com/blife/blife/global/exception/InvalidCredentialException.kt
  src/main/kotlin/com/blife/blife/global/security/JwtPlugin.kt
  src/main/resources/application.yml
Labels: Feature

#26 Feat/#22
  src/main/kotlin/com/blife/blife/domain/book/application/BookUseCase.kt
  src/main/kotlin/com/blife/blife/domain/book/model/Book.kt
  src/main/kotlin/com/blife/blife/domain/book/repository/IBookRepository.kt
  src/main/kotlin/com/blife/blife/domain/book/service/BookService.kt
  src/main/kotlin/com/blife/blife/infra/external/booksearchapi/IBookSearchClient.kt
  src/main/kotlin/com/blife/blife/infra/external/booksearchapi/KakaoBookSearchClient.kt
  src/main/kotlin/com/blife/blife/infra/external/booksearchapi/NaverBookSearchClient.kt
  src/main/kotlin/com/blife/blife/infra/external/booksearchapi/dto/kakao/KakaoBookSearchResponseDocument.kt
  src/main/kotlin/com/blife/blife/infra/external/booksearchapi/dto/naver/NaverBookSearchResponseItem.kt
  src/main/kotlin/com/blife/blife/infra/postgresql/book/BookEntity.kt
  src/main/kotlin/com/blife/blife/infra/postgresql/book/JpaBookRepository.kt
  src/main/kotlin/com/blife/blife/infra/postgresql/book/PostgresqlBookRepository.kt
  src/main/kotlin/com/blife/blife/infra/postgresql/book/QueryDslBookRepository.kt
  src/test/kotlin/com/blife/blife/domain/book/application/BookEntityUseCaseTest.kt
Labels: Bugfix, Feature, Refactor

#32 Feat/#31
  src/main/kotlin/com/blife/blife/domain/book/controller/BookController.kt
  src/main/kotlin/com/blife/blife/domain/book/controller/dto/BookResponse.kt
  src/main/kotlin/com/blife/blife/infra/external/booksearchapi/dto/kakao/KakaoBookSearchResponseDocument.kt
  src/main/kotlin/com/blife/blife/infra/external/booksearchapi/dto/naver/NaverBookSearchResponseItem.kt
  src/test/kotlin/com/blife/blife/domain/book/application/BookEntityUseCaseTest.kt
Labels: Feature, Refactor, test

#60 Bugfix: yml 파일 .env에서 끌고 오는 key값 대문자로 변경
  .github/workflows/ci-workflow.yaml
  src/main/kotlin/com/blife/blife/infra/external/booksearchapi/client/NaverBookSearchClient.kt
  src/main/kotlin/com/blife/blife/infra/external/libapi/Data4libClient.kt
  src/main/resources/application.yml
Labels: Bugfix

#63 Feat/#34 대출 반납시 찜 메일 알림 구현 및 들여쓰기 수정
  src/main/kotlin/com/blife/blife/domain/book/service/BookService.kt
  src/main/kotlin/com/blife/blife/domain/book/service/LibBookService.kt
  src/main/kotlin/com/blife/blife/domain/checkoutbook/controller/CheckoutController.kt
  src/main/kotlin/com/blife/blife/domain/checkoutbook/dto/CheckoutRequest.kt
  src/main/kotlin/com/blife/blife/domain/checkoutbook/dto/CheckoutResponse.kt
  src/main/kotlin/com/blife/blife/domain/checkoutbook/dto/LibBookStatusResponse.kt
  src/main/kotlin/com/blife/blife/domain/checkoutbook/dto/ReturnBookRequest.kt
  src/main/kotlin/com/blife/blife/domain/checkoutbook/dto/ReturnBookResponse.kt
  src/main/kotlin/com/blife/blife/domain/checkoutbook/model/CheckoutBook.kt
  src/main/kotlin/com/blife/blife/domain/checkoutbook/repository/CheckoutRepository.kt
  src/main/kotlin/com/blife/blife/domain/checkoutbook/service/CheckoutService.kt
  src/main/kotlin/com/blife/blife/domain/mail/service/MailService.kt
  src/main/kotlin/com/blife/blife/domain/mail/service/MemberMailService.kt
  src/main/kotlin/com/blife/blife/domain/wishlist/model/WishList.kt
  src/main/kotlin/com/blife/blife/domain/wishlist/repository/WishListRepository.kt
  src/main/kotlin/com/blife/blife/domain/wishlist/service/WishService.kt
Labels: Feature, Refactor

#66 Test: 외부 API 호출 테스트 코드
  src/test/kotlin/com/blife/blife/infra/external/booksearchapi/KakaoBookSearchClientTest.kt
  src/test/kotlin/com/blife/blife/infra/external/booksearchapi/NaverBookSearchClientTest.kt
  src/test/kotlin/com/blife/blife/infra/external/libapi/data4library/Data4libClientTest.kt
Labels: test

#79 Bugfix: Kakao API 호출 시 에러 발생
  src/main/kotlin/com/blife/blife/infra/external/booksearchapi/client/KakaoBookSearchClient.kt
  src/main/kotlin/com/blife/blife/infra/external/booksearchapi/dto/kakao/KakaoBookSearchResponseDocument.kt
Labels: Bugfix

#83 Bugfix/#75
  src/main/kotlin/com/blife/blife/domain/checkoutbook/controller/CheckoutController.kt
  src/main/kotlin/com/blife/blife/domain/checkoutbook/model/CheckoutBook.kt
  src/main/kotlin/com/blife/blife/domain/checkoutbook/service/CheckoutService.kt
  src/main/kotlin/com/blife/blife/domain/member/model/Member.kt
  src/main/kotlin/com/blife/blife/infra/postgresql/library/JpaLibraryRepository.kt
Labels: Bugfix

#82 Feat/#81: SecurityConfig 추가 작업
  src/main/kotlin/com/blife/blife/domain/member/service/MemberService.kt
  src/main/kotlin/com/blife/blife/global/config/SecurityConfig.kt
Labels: Feature
